In [36]:
# !pip install geopy

In [37]:
import pandas as pd
import numpy as np
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

In [38]:
east_data = pd.read_csv("C:/Users/ohesu/Documents/FIELD_CAMP/drive-download-20230802T063712Z-001/데이터/데이터/3. 멀어야하는 공공시설/유흥시설_동구.csv", encoding='cp949')
middle_data = pd.read_csv("C:/Users/ohesu/Documents/FIELD_CAMP/drive-download-20230802T063712Z-001/데이터/데이터/3. 멀어야하는 공공시설/유흥시설_중구.csv", encoding='cp949')
factory_data = pd.read_csv("C:/Users/ohesu/Documents/FIELD_CAMP/drive-download-20230802T063712Z-001/데이터/데이터/3. 멀어야하는 공공시설/인천광역시_공장등록 현황_20230531.csv", encoding='cp949')

In [39]:
# 중구와 동구의 데이터만 추ㅜㄹ
true_index = (factory_data['시군구'] == '중구') | (factory_data['시군구'] == '동구')
processed_factory_data = factory_data[true_index]

In [41]:
for data in [east_data,middle_data,processed_factory_data]:
    new_address = []
    for address in data['소재지']:
        a = address.split(' ')
        address = " ".join(a[0:4])
        new_address.append(address)
    data['소재지'] = new_address

C:\Users\ohesu\AppData\Local\Temp\ipykernel_9156\2405493772.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['소재지'] = new_address

In [42]:
east_data

   순번     업종명        업소명                 소재지         소재지전화
0   1  유흥주점영업        강능집   인천광역시 동구 금곡로 91-1  032-766-1858
1   2  유흥주점영업     불꽃노래클럽    인천광역시 동구 샛골로 143  032-773-7030
2   3  유흥주점영업         루비    인천광역시 동구 수문통로 17  032-773-7774
3   4  유흥주점영업     현대노래클럽    인천광역시 동구 샛골로 147           NaN
4   5    단란주점  멍텅구리 단란주점    인천광역시 동구 샛골로 170  032-773-2480
5   6    단란주점        스카렛    인천광역시 동구 화도진로 68  032-772-3769
6   7    단란주점        지중해  인천광역시 동구 샛골로 158-2  032-773-9390
7   8    단란주점    쇼노래단란주점   인천광역시 동구 샛골로 143,  032-773-4449
8   9    단란주점         쩜프      인천광역시 동구 송현로 1           NaN

In [43]:
# Geopy 초기화
geolocator = Nominatim(user_agent="South Korea")

# 위경도 획득 함수
def geocoding(address):
    try:
        geo = geo_local.geocode(address)
        x_y = [geo.latitude, geo.longitude]
        return x_y
    except:
        return [0,0]

In [45]:
for data in [east_data,middle_data,processed_factory_data]:
    latitude = []
    longitude =[]
    for address in data['소재지']:
        latitude.append(geocoding(address)[0])
        longitude.append(geocoding(address)[1])
    data['X'] = longitude
    data['Y'] = latitude

C:\Users\ohesu\AppData\Local\Temp\ipykernel_9156\2869620704.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Y'] = latitude
C:\Users\ohesu\AppData\Local\Temp\ipykernel_9156\2869620704.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['X'] = longitude

In [48]:
east_data
middle_data

,업종명,업소명,소재지,소재지전화,데이터기준일자,Y,X
0,유흥주점영업,위스키메리(외국인전용),인천광역시 중구 개항로 5,NaN,2023-07-05,0,0
1,유흥주점영업,디가디가노래타운,인천광역시 중구 홍예문로98번길 9,032 -772 -7542,2023-07-05,0,0
2,유흥주점영업,향도 노래천국,인천광역시 중구 서해대로 462-3,032 - 883-5611,2023-07-05,0,0
3,유흥주점영업,거래처,인천광역시 중구 신포로27번길 32,032 - 765-2430,2023-07-05,0,0
4,유흥주점영업,미,인천광역시 중구 신포로23번길 32,032 - 762-4443,2023-07-05,0,0
...,...,...,...,...,...,...,...
136,단란주점,채플린,"인천광역시 중구 연안부두로33번길 24,",070 -4353-0771,2023-07-05,0,0
137,단란주점,두바이 노래타운,"인천광역시 중구 은하수로29번길 47,",NaN,2023-07-05,0,0
138,단란주점,노래하는 술창고,"인천광역시 중구 연안부두로 13,",NaN,2023-07-05,0,0
139,단란주점,헤이노래타운,"인천광역시 중구 신도시남로141번길 9,",NaN,2023-07-05,0,0
140,단란주점,거해7080,"인천광역시 중구 은하수로 28,",032 -746 -2270,2023-07-05,0,0

In [ ]:
read